---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: jenkins
  name: jenkins
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - name: jenkins
          image: laitrio/lok-jenkins:0.1.0
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /var/jenkins_home/init.groovy.d
              name: initialization
          env:
            - name: ADMIN_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: jenkins-credentials
                  key: user.name
            - name: ADMIN_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: jenkins-credentials
                  key: user.password
      volumes:
        - name: initialization
          configMap:
            name: jenkins-security
            items:
              - key: security.groovy
                path: security.groovy
              - key: _security.groovy
                path: _security.groovy
