sudo: required

language: groovy

services:
  - docker

install:
  - sudo apt-get install yamllint
  - docker pull lukasmartinelli/hadolint

script:
  - docker run --rm -i lukasmartinelli/hadolint < Dockerfile
  - yamllint deployments/ services/

