sudo: required

language: python

services:
  - docker

install:
  - pip install yamllint
  - docker pull lukasmartinelli/hadolint

script:
  - docker run --rm -i lukasmartinelli/hadolint < Dockerfile
  - yamllint deployments/ services/

