---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: jenkins
  name: jenkins
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      name: ui
    - port: 8081
      protocol: TCP
      targetPort: 8081
      name: jnlp
  selector:
    app: jenkins
  type: LoadBalancer
